### ISSUE TITLE
Add GET IT on F-Droid badge

### ISSUE THREAD

**Issue by PanderMusubi** [trmendes/BirthDayDroid#2]
Please, add a GET IT on F-Droid badge

**Comment by PanderMusubi** [comment]
in the README.md file.

**Comment by trmendes** [comment]
Will do it as soon as I have a computer

**Comment by PanderMusubi** [comment]
If I may ask, why did you close this?

**Comment by trmendes** [comment]
Sorry @PanderMusubi

My bad...reopened... And I'll fix it when I have a computer

**Comment by revuwa** [comment]
Ready to go, if you like:

#### Links

[<img src="https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png"
      alt="Get it on Google Play"
      height="80">](https://play.google.com/store/apps/details?id=com.tmendes.birthdaydroid)
[<img src="https://f-droid.org/badge/get-it-on.png"
      alt="Get it on F-Droid"
      height="80">](https://f-droid.org/app/com.tmendes.birthdaydroid)

**Comment by trmendes** [comment]
Thanks for your help :D
