### ISSUE TITLE
(non-daily) birthday notifications issue

### ISSUE THREAD

**Issue by revuwa** [trmendes/BirthDayDroid#5]
First of all, thanks for that great app and for sharing it with the world.

I'm struggling a bit with the birthday notifications.
I would like to get informed a few days in advance, and then at the day of event.
So I enabled 'Birthday notifcations in advance [X]' and set the days I want in 'Days in advance'.
Everything is working well, if the checkbox 'Daily notifications [X]' is checked, too.

But then I got (suprise) daily notifications, which I don't want.
I really just want one notification a few days before, then silence, and finally at the day of event again.
So I disabled 'Daily notifications [_]', but in this case I don't get any notifications anymore.
None a few days before, and nothing at the day of event.

It would be very cool, if I could get notifications as described (without the daily reminder), please.

**Comment by trmendes** [comment]
Thanks for your msg @revuwa ...I'm gonna check it as soon as possible :)
