### ISSUE TITLE
Update/refresh data when contact is edited

### ISSUE THREAD

**Issue by rugk** [trmendes/BirthDayDroid#6]
When I edit the contact's birthday from the app and return to it, it still shows me the old (wrong) age and so on…
I have to exit the app (swipe it away in the "last apps" screen) and restart it and only then the data is refreshed and correctly shown.

**Comment by trmendes** [comment]
Thanks @rugk ....fixed on the bug/issue6 branch. Gonna bring it to the master as soon as I fix another bugs here.
